# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Repast
email: ncollier@anl.gov
# description: > Repast
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://repast.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  Repast

exclude:
 - scripts/

include:
  - _*.html

simphony_version: 2.10.0
simphony_release_date: 22 December 2022
hpc_version: 2.3.1
hpc_release_date: 21 October 2021
r4py_version: 1.0.5beta1
r4py_release_date: 17 October 2022

# Build settings
markdown: kramdown
theme: minima

github: [metadata]
kramdown:
   input: GFM
   hard_wrap: false
#gems:
   #- jekyll-coffeescript
   #- jekyll-paginate
